### ISSUE TITLE
TypeError: Cannot read property 'upstream' of undefined 

### ISSUE THREAD

**Issue by noipstream** [pr0sessor/ethash-multicoin-pool#1]
root@alien:/pool/ethash-multicoin-pool# node src/init.js --stratum --coin=ethereum
/pool/ethash-multicoin-pool/src/lib/index.js:30
const upstream = new Upstream(config.stratum.coins[coin].upstream)
                                                         ^

TypeError: Cannot read property 'upstream' of undefined
    at Object.<anonymous> (/pool/ethash-multicoin-pool/src/lib/index.js:30:58)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at NativeConnection.<anonymous> (/pool/ethash-multicoin-pool/src/init.js:18:5)
    at Object.onceWrapper (events.js:286:20)
    at NativeConnection.emit (events.js:198:13)
    at NativeConnection.Connection.onOpen (/pool/ethash-multicoin-pool/node_modules/mongoose/lib/connection.js:646:8)
    at _setClient (/pool/ethash-multicoin-pool/node_modules/mongoose/lib/connection.js:998:8)
    at client.connect (/pool/ethash-multicoin-pool/node_modules/mongoose/lib/connection.js:840:7)
    at /pool/ethash-multicoin-pool/node_modules/mongodb/lib/utils.js:704:5
    at err (/pool/ethash-multicoin-pool/node_modules/mongodb/lib/mongo_client.js:261:7)

**Comment by Konstantin35** [comment]
> 

`node src/init.js --backend --stratum --coin=ethereum --cron`
